steps:
- name: gcr.io/cloud-builders/git
  id: variables
  entrypoint: 'bash'
  args:
    - -c 
    - |
      # store multiple values as environment variables
      # name all values with a common prefix (we'll use "build_")
      if [ "$BRANCH_NAME" = "main" ]
      then
        export build_profile="test"
        export build_path="/workspace/app-mod/cicd-cloudbuild"
      elif [ "$BRANCH_NAME" = "prod" ]
      then
        export build_profile="prod"
        export build_path="/workspace/app-mod/cicd-cloudbuild"
      else
        export build_profile="test"
        export build_path="."
      fi

      export build_prefix="" 
      export build_token=$(gcloud auth application-default print-access-token)

      # write all "build_" variables to the persistent volume "/workspace"
      env | grep "^build_" > /workspace/build_vars
- name: 'gcr.io/cloud-builders/mvn'
  id: deploy
  entrypoint: 'bash'
  args:
    - -c 
    - |
      # Read environment variables from disk
      source /workspace/build_vars &&
      mvn -f ${build_path}/cloudbuild-pom.xml -ntp clean install -P${build_profile} -Dorg=$PROJECT_ID -Ddeployment.suffix=${build_prefix} -Dbearer=${build_token} 
