const express = require('express')
const app = express()
const port = 8080

app.post('/offer', (req, res) => {
  res.send({"loan_offers":{"element":[{"charges_and_fees":{"record":{"element":{"amount":{"amount":25,"currency":"GBP"},"type":"SETUP"}}},"hal_links":{"consent":{"href":"a","uri_template":"true"},"loan_offers":{"element":{"href":"a","uri_template":"true"}}},"interest_rate":{"element":{"rate":2}},"loan_offer_resource_identification":"FSICORE_SDS_2015_LO9744","principal_amount":{"amount":1195.65,"currency":"GBP"},"purpose":{"description":"Pixelbook Pro 64GB Home Use","line_item":{"element":{"identification":"Pixelbook Pro 64GB Home Use"}}},"total_loan_cost":{"amount":1190.65,"currency":"GBP"},"tranche":{"element":[{"due_date":"2020-11-22","interest_amount":{"amount":2.95,"currency":"GBP"},"last_tranche_indicator":"false","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0001"},{"due_date":"2020-12-22","interest_amount":{"amount":1.7,"currency":"GBP"},"last_tranche_indicator":"false","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0002"},{"due_date":"2021-01-22","interest_amount":{"amount":1,"currency":"GBP"},"last_tranche_indicator":"true","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0003"}]},"validity_date":{"date_time":{"from_date_time":"2020-10-22","to_date_time":"2020-10-29"}}},{"charges_and_fees":{"record":{"element":{"amount":{"amount":30,"currency":"GBP"},"type":"SETUP"}}},"hal_links":{"consent":{"href":"a","uri_template":"true"},"loan_offers":{"element":{"href":"a","uri_template":"true"}}},"interest_rate":{"element":{"rate":2}},"loan_offer_resource_identification":"FSICORE_SDS_2015_LO3174","principal_amount":{"Amount":1195.65,"currency":"GBP"},"purpose":{"description":"Pixelbook Pro 64GB Home Use","line_item":{"element":{"identification":"Pixelbook Pro 64GB Home Use"}}},"total_loan_cost":{"amount":1190.65,"currency":"GBP"},"tranche":{"element":[{"due_date":"2020-11-22T13:37:21.866Z","interest_amount":{"amount":2.95,"currency":"GBP"},"last_tranche_indicator":"false","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0001"},{"due_date":"2020-12-22T13:37:21.866Z","interest_amount":{"amount":1.7,"currency":"GBP"},"last_tranche_indicator":"false","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0002"},{"due_date":"2021-01-22T13:37:21.866Z","interest_amount":{"amount":1,"currency":"GBP"},"last_tranche_indicator":"true","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0003"}]},"validity_date":{"date_time":{"from_date_time":"2020-10-22","to_date_time":"2020-10-29"}}}]}})
})

app.get('/offer', (req, res) => {
  res.send({"loan_offers":{"element":[{"charges_and_fees":{"record":{"element":{"amount":{"amount":25,"currency":"GBP"},"type":"SETUP"}}},"hal_links":{"consent":{"href":"a","uri_template":"true"},"loan_offers":{"element":{"href":"a","uri_template":"true"}}},"interest_rate":{"element":{"rate":2}},"loan_offer_resource_identification":"FSICORE_SDS_2015_LO9744","principal_amount":{"amount":1195.65,"currency":"GBP"},"purpose":{"description":"Pixelbook Pro 64GB Home Use","line_item":{"element":{"identification":"Pixelbook Pro 64GB Home Use"}}},"total_loan_cost":{"amount":1190.65,"currency":"GBP"},"tranche":{"element":[{"due_date":"2020-11-22","interest_amount":{"amount":2.95,"currency":"GBP"},"last_tranche_indicator":"false","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0001"},{"due_date":"2020-12-22","interest_amount":{"amount":1.7,"currency":"GBP"},"last_tranche_indicator":"false","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0002"},{"due_date":"2021-01-22","interest_amount":{"amount":1,"currency":"GBP"},"last_tranche_indicator":"true","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0003"}]},"validity_date":{"date_time":{"from_date_time":"2020-10-22","to_date_time":"2020-10-29"}}},{"charges_and_fees":{"record":{"element":{"amount":{"amount":30,"currency":"GBP"},"type":"SETUP"}}},"hal_links":{"consent":{"href":"a","uri_template":"true"},"loan_offers":{"element":{"href":"a","uri_template":"true"}}},"interest_rate":{"element":{"rate":2}},"loan_offer_resource_identification":"FSICORE_SDS_2015_LO3174","principal_amount":{"Amount":1195.65,"currency":"GBP"},"purpose":{"description":"Pixelbook Pro 64GB Home Use","line_item":{"element":{"identification":"Pixelbook Pro 64GB Home Use"}}},"total_loan_cost":{"amount":1190.65,"currency":"GBP"},"tranche":{"element":[{"due_date":"2020-11-22T13:37:21.866Z","interest_amount":{"amount":2.95,"currency":"GBP"},"last_tranche_indicator":"false","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0001"},{"due_date":"2020-12-22T13:37:21.866Z","interest_amount":{"amount":1.7,"currency":"GBP"},"last_tranche_indicator":"false","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0002"},{"due_date":"2021-01-22T13:37:21.866Z","interest_amount":{"amount":1,"currency":"GBP"},"last_tranche_indicator":"true","principal_amount":{"amount":395,"currency":"GBP"},"tranche_number":"T0003"}]},"validity_date":{"date_time":{"from_date_time":"2020-10-22","to_date_time":"2020-10-29"}}}]}})
})

app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})
